apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-host
  name: redis-host
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: redis-host
status:
  loadBalancer: {}
