apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\BIN\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-host
  name: redis-host
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-host
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\BIN\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-host
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: ""
        name: redis-host
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
